// Add-on products with Stripe price IDs
export const ADDON_PRODUCTS = {
  "motion-upgrade": {
    id: "motion-upgrade",
    title: "Motion Upgrade",
    price: 45.00,
    priceId: "price_1SdKPOFTlHtQpdKRzXubCXsl",
    description: "Animated version of your cover art for social media.",
    image: "/addons/motion-cover.gif",
  },
  "spotify-canvas": {
    id: "spotify-canvas",
    title: "Spotify Canvas",
    price: 25.00,
    priceId: "price_1SdKPaFTlHtQpdKRpxK6TbnR",
    description: "8-second loop video for Spotify backgrounds.",
    image: "/addons/spotify-canvas.gif",
  },
  "apple-music-motion": {
    id: "apple-music-motion",
    title: "Apple Music Motion Cover",
    price: 40.00,
    priceId: "price_1SdKR6FTlHtQpdKRbPY4GiHv",
    description: "Animated artwork for Apple Music.",
    image: "/addons/apple-music-motion.gif",
  },
  "song-promo-video": {
    id: "song-promo-video",
    title: "Song Promo Video",
    price: 29.99,
    priceId: "price_1SdKRNFTlHtQpdKRsbp4Zpqd",
    description: "15-second teaser video with audio visualizer.",
    image: "/addons/song-promo-video.gif",
  },
  "motion-promo-ad": {
    id: "motion-promo-ad",
    title: "Motion Promo Ad",
    price: 14.99,
    priceId: "price_1SdKRaFTlHtQpdKR1yPAztNJ",
    description: "High-energy promotional motion ad.",
    image: "/addons/motion-promo-ad.gif",
  },
  "motion-promo-billboard": {
    id: "motion-promo-billboard",
    title: "Motion Promo Billboard",
    price: 14.99,
    priceId: "price_1SdKRnFTlHtQpdKRbXIstENT",
    description: "Digital billboard style animation.",
    image: "/addons/motion-promo-billboard.gif",
  },
  "promo-ads-texture": {
    id: "promo-ads-texture",
    title: "Promo Ads Texture",
    price: 10.99,
    priceId: "price_1SdKRzFTlHtQpdKReibcccfV",
    description: "Textured promotional graphic assets.",
    image: "/addons/promo-ads-texture.jpg",
  },
  "promo-ads-phone": {
    id: "promo-ads-phone",
    title: "Promo Ads Phone",
    price: 10.99,
    priceId: "price_1SdKSGFTlHtQpdKR694Lnwuh",
    description: "Social media phone mockup promotion.",
    image: "/addons/promo-ads-phone.jpg",
  },
  "spotify-banner": {
    id: "spotify-banner",
    title: "Spotify Banner",
    price: 12.99,
    priceId: "price_1SdKSTFTlHtQpdKRYTlaFFlD",
    description: "Professional header for your Spotify profile.",
    image: "/addons/spotify-banner.jpg",
  },
  "youtube-screen": {
    id: "youtube-screen",
    title: "YouTube Screen",
    price: 12.99,
    priceId: "price_1SdKSeFTlHtQpdKRfYl2T7DG",
    description: "Branded screen overlay for YouTube videos.",
    image: "/addons/youtube-screen.jpg",
  },
  "tracklist-design": {
    id: "tracklist-design",
    title: "Tracklist Design",
    price: 19.99,
    priceId: "price_1SdKSrFTlHtQpdKRHs13bHNo",
    description: "Matching back cover with your song list.",
    image: "/addons/tracklist-design.jpg",
  },
  "lyric-video": {
    id: "lyric-video",
    title: "Lyric Video",
    price: 45.00,
    priceId: "price_1SdKT2FTlHtQpdKRW3kRWyLE",
    description: "Full animated lyric video for your track.",
    image: "/addons/lyric-video.jpg",
  },
} as const;

export type AddonId = keyof typeof ADDON_PRODUCTS;
