// Text Style Variants Configuration
// Only 5 styles available: Creative, Dark, Futuristic, Modern, Retro

export interface TextStyleVariant {
  id: string;
  name: string;
  description: string;
  previewImage: string; // URL to preview image (in public/text-styles/)
  promptInstructions: string; // Detailed AI prompt for this exact style
  referenceImages?: string[]; // Additional reference images for AI
}

export interface TextStyleWithVariants {
  id: string;
  name: string;
  description: string;
  example: string;
  prompt: string;
  variants: TextStyleVariant[];
}

// Detailed descriptions for each creative variant - MUST MATCH PREVIEW IMAGES
// These are EXTENSIVE prompts designed for AI image generation accuracy
const CREATIVE_VARIANT_DESCRIPTIONS: Record<number, string> = {
  1: "TYPOGRAPHY STYLE: Elegant flowing white brush script calligraphy with soft ethereal glow and MOTION BLUR edges. LETTERFORMS: Organic, hand-painted cursive with natural brush stroke variations, thick-to-thin transitions. CRITICAL EFFECT - MOTION/ZOOM BLUR: The FIRST 1-2 letters and LAST 1-2 letters of the song title MUST have a horizontal motion blur/zoom blur effect - letters appear to be fading/blurring into motion at the edges, like they're zooming in from the sides. The center letters remain sharp and crisp. EFFECTS: Soft white light bloom/halo around text, dreamy luminescence, edge letters dissolving into directional motion blur streaks. COLOR: Pure white text with soft gray shadows on dark background. MOOD: Romantic, ethereal, premium wedding invitation aesthetic with cinematic motion feel.",
  
  2: "TYPOGRAPHY STYLE: Heavy distressed uppercase industrial sans-serif with aggressive grunge texture. LETTERFORMS: Bold, blocky condensed letters with rough eroded edges, paint splatter, and worn-away sections. EFFECTS: Spray paint overspray, ink splatter marks, scratched and weathered surface texture. COLOR: Off-white/gray text with heavy black distress marks on dark background. MOOD: Street art, punk rock poster, urban decay aesthetic.",
  
  3: "TYPOGRAPHY STYLE: Ultra-bold chunky distorted display font with HORIZONTAL BLUR/LIQUIFY LINES cutting through the text. LETTERFORMS: Extremely thick, heavy sans-serif with inconsistent letter sizes - some letters much larger than others creating dynamic visual rhythm. CRITICAL EFFECT - LIQUIFY DISTORTION LINES: There MUST be 2-3 horizontal wavy blur/liquify distortion lines running THROUGH the text - these lines warp and smear the letters where they cross, creating a glitchy/liquid warp effect. The lines stretch and blur the letterforms horizontally as if the text was liquified in those areas. EFFECTS: Horizontal liquify wave distortions cutting through letters, slight perspective warping, glitch-like horizontal smear bands. COLOR: High contrast black and white. MOOD: Bold, impactful, glitchy modern poster design, attention-grabbing distortion aesthetic.",
  
  4: "TYPOGRAPHY STYLE: ULTRA TALL condensed EXTRA-BOLD SANS-SERIF with WAVY SLANTED distortion. CRITICAL WEIGHT - MUST BE EXTRA BOLD: Letters must be THICK, CHUNKY, and HEAVY - never thin or light weight. Stroke width should be substantial and commanding. CRITICAL - MUST BE SANS-SERIF: Absolutely NO serifs, NO decorative flourishes, NO thin strokes - clean geometric sans-serif letterforms only (like Impact, Bebas Neue Bold, or Black weight condensed fonts). LETTERFORMS: Extremely tall and narrow uppercase letters with VERY THICK stroke weight, letters touching or nearly touching (extremely tight letter spacing). CRITICAL WAVY EFFECT: The letters have a pronounced WAVE/SLANT distortion - they curve and lean dynamically. The vertical strokes curve slightly creating an organic wave pattern across the word. NEVER use thin fonts. NEVER use serif fonts. COLOR: White or colored text on dark background. MOOD: Bold impactful headlines with dynamic wavy energy.",
  
  5: "TYPOGRAPHY STYLE: EXTREMELY DISTRESSED GRUNGE SANS-SERIF with ONE MAJOR JAGGED CRACK. CRITICAL - MUST BE SANS-SERIF: Heavy bold geometric sans-serif (like Impact), NO serifs, NO glow. LETTERFORMS: Thick, bold, uppercase with MAXIMUM DISTRESS - rough eroded edges, chunks missing, heavily worn and damaged appearance. ABSOLUTE REQUIREMENT - JAGGED CRACK: There MUST ALWAYS be ONE SIGNIFICANT JAGGED CRACK running diagonally through the ENTIRE text from one side to the other - this crack is TRANSPARENT showing the background through it. The crack should be irregular and jagged like cracked concrete or shattered stone, cutting completely through multiple letters. This crack is NON-NEGOTIABLE and must be prominent and visible. EXTREME DISTRESS TEXTURE: Letters must look SEVERELY weathered - rough pitted surface like old concrete, paint peeling, eroded edges, visible wear and damage throughout. The letters should look ancient, broken, and beaten. Every letter should have visible damage, rough edges, and distress marks. CRITICAL COLOR INTEGRATION: The text color MUST harmonize and integrate with the cover artwork's color palette - NOT always beige/brown. Analyze the dominant colors in the background artwork and choose a distressed text color that complements and belongs with the scene. For warm/red backgrounds use warm earth tones, for cool backgrounds use gray-blue tones, for green/nature use mossy tones, etc. The text should feel like part of the artwork, not pasted on. The color should be muted and weathered to match the distressed style. MOOD: Post-apocalyptic, destroyed, maximum grunge and decay. NO CLEAN EDGES, NO SMOOTH SURFACES.",
  
  6: "TYPOGRAPHY STYLE: GLITCHED METALLIC CHROME TEXT with severe digital corruption and fragmentation. LETTERFORMS: Bold, italic condensed sans-serif with chrome/silver metallic finish, letters breaking apart horizontally. EFFECTS: CRITICAL - Heavy horizontal glitch lines slicing through text, pixel displacement, digital scan line artifacts, data corruption blocks, RGB color separation on edges, scattered pixel debris around letters. COLOR: Silver/chrome metallic gradient with white highlights, black glitch blocks, grayscale corruption artifacts. MOOD: Cyberpunk, corrupted data, VHS tracking error, digital dystopia aesthetic. The text should look like it's being destroyed by a computer virus or signal interference.",
  
  7: "TYPOGRAPHY STYLE: BLURRY GLOWING TEXT with EXTREME CHAOTIC MELTING/DISSOLVING BOTTOM. LETTERFORMS: Bold uppercase, entire text has soft blur/glow. CRITICAL - EXTREME BOTTOM DISSOLUTION (5X INTENSITY): The BOTTOM THIRD of each letter MUST have MASSIVELY EXAGGERATED melting, warping, blurring, and fading. The bottom portion should be COMPLETELY DESTROYED - ultra blurry, extremely warped and distorted, chaotically melting, and FADING TO NOTHING. The melting should extend FAR below the letters with maximum blur and distortion. Letters should look like they are violently dissolving, melting into oblivion with intense warping. The bottom portions become SO BLURRY they are nearly invisible, fading to complete transparency. This dissolution effect must be EXTREME, CHAOTIC, and DRAMATIC - not subtle. The warping should twist and distort the melting portions beyond recognition. Think of letters being disintegrated from the bottom up - maximum destruction, maximum blur, maximum fade. The effect should be 5X more intense than normal melting text. COLOR: White/light glowing text on dark background. MOOD: Violently dissolving, extreme warped melting, fading into void.",
  
  8: "TYPOGRAPHY STYLE: BOLD SERIF with TOP THIRD COMPLETELY BLURRED OUT. LETTERFORMS: BOLD, HEAVY serif font with subtle serifs and thick strokes - NOT thin like Times New Roman. The font should have substantial weight and presence, with refined but minimal serifs. Think bold display serif, not book text serif. CRITICAL BLOWN OUT TOP: The TOP THIRD of each letter itself MUST be COMPLETELY BLURRED OUT and FADING - the actual letterforms dissolve into extreme blur at the top, becoming transparent and disappearing into wispy mist. The bottom 2/3 of letters are more solid and readable, but the top third of every letter blurs out dramatically into fading mist/smoke that extends above. This blur is part of the letters themselves, not just effects above them. The transition from solid to blurred should be dramatic. COLOR: Any color that matches the cover vibe - the text should complement the artwork. MOOD: Ethereal, fading away, dissolving upward into mist, dramatic blown out effect. CRITICAL: Font must be BOLD with weight, not thin. Top third COMPLETELY blurred.",
  
  9: "TYPOGRAPHY STYLE: TEXT MADE ENTIRELY OF SMOKE/FOG with WISPS EXPANDING THROUGHOUT. LETTERFORMS: THIN, elegant script or serif letters that appear to be COMPLETELY FORMED FROM SMOKE - the letters themselves are made of swirling smoke, mist, and fog. NOT solid letters with smoke effects - the actual letterforms ARE smoke. CRITICAL SMOKE EFFECT: The entire text must look like it is constructed from wispy, swirling smoke. Smoke wisps and tendrils should extend and expand OUT from all parts of every letter - top, bottom, sides - as if the text is disintegrating and dissolving into the air. The letters should have a thin, ethereal quality with smoke particles and wisps floating away in all directions. TEXTURE: Soft, translucent smoke texture throughout. The edges of letters are undefined and wispy, blending into smoke trails. The text should feel like it could disappear at any moment - fragile and ephemeral. COLOR: Gray/white smoke on dark background, or smoke color that complements the cover. MOOD: Ethereal, ghostly, disintegrating, vanishing into mist and fog. The text is MADE OF SMOKE, not text with smoke added.",
  
  10: "TYPOGRAPHY STYLE: BOLD HEAVY liquid chrome mercury metallic text with mirror reflections. LETTERFORMS: THICK, BLOCKY, HEAVY WEIGHT sans-serif or slab serif - NOT thin or rounded. The letters should be MASSIVE and BOLD with substantial stroke weight, appearing as thick slabs of liquid metal. Think heavy industrial chrome, not delicate mercury. EFFECTS: Perfect mirror reflections of environment, chrome specular highlights, liquid surface tension appearance, water droplets on metal surface. COLOR: Silver chrome with reflected colors from surroundings, bright white highlights and deep shadows for dimension. MOOD: Premium luxury, powerful, industrial strength, high-end product design. CRITICAL: Letters must be BOLD and HEAVY with thick strokes - NOT thin or wispy."
};

const DARK_VARIANT_DESCRIPTIONS: Record<number, string> = {
  1: "TYPOGRAPHY STYLE: Gothic blackletter with chrome metallic finish and sparkle effects. LETTERFORMS: Sharp, pointed medieval blackletter with dramatic angular serifs and high contrast thick/thin strokes. EFFECTS: Mirror-finish chrome surface, small star sparkle highlights scattered around text, sharp pointed terminals. COLOR: Silver chrome with bright white specular highlights on black background. MOOD: Medieval dark fantasy, heavy metal album art, royal gothic luxury.",
  
  2: "TYPOGRAPHY STYLE: BOLD DEATH METAL / BLACK METAL typography with sharp angular extensions and spikes. LETTERFORMS: THICK, HEAVY, BOLD uppercase letters with substantial stroke weight - the letters themselves are CHUNKY and POWERFUL, not thin or delicate. Letters have blackletter-inspired angular forms with sharp pointed spike extensions shooting outward from letters. CRITICAL BOLDNESS: The main letter strokes must be THICK and HEAVY with significant visual weight. This is not thin wispy metal text - it's BOLD and SOLID with meaty letterforms. SPIKE EXTENSIONS: Letters have sharp pointed extensions and blade-like protrusions extending outward, but these are MODERATE in length and quantity - not extremely long or overwhelming. The spikes are accent elements that enhance the aggressive feel without making letters illegible. Some spikes curve and hook, others are straight. The spikes are decorative but don't dominate the composition. LETTER STRUCTURE: The core letterforms are clearly readable despite the aggressive styling. Thick vertical strokes form the body of each letter with dramatic thick-to-thin contrast. Angular distortions are present but letters maintain their identity. TEXTURE: Metallic sheen with chrome/silver highlights and subtle dark cracks or weathering on the metal surface. SPACING: Letters can overlap slightly with spikes interweaving, but maintain readability. COLOR: Silver/white metallic text with sharp highlights on pure black background. MOOD: Death metal album art, extreme music, aggressive but READABLE metal typography. Bold and powerful, not thin and chaotic.",
  
  3: "TYPOGRAPHY STYLE: TALL FLOWING GOTHIC typography with SMOOTH CURVED organic lines - NOT rigid or straight. LETTERFORMS: TALL and moderately narrow uppercase letters with an ELEGANT FLOWING CURVATURE throughout. The letters have a gothic/horror feel but with SMOOTH, ORGANIC CURVED strokes - every vertical stroke has a subtle FLOWING CURVE or gentle arc to it, NOT straight rigid lines. CRITICAL CURVED QUALITY: The key characteristic is SMOOTH FLOWING CURVES within the letterforms. Vertical strokes bow and curve gracefully. Horizontal and connecting strokes have elegant arcs. The overall effect is organic and flowing like tendrils or vines, NOT mechanical or rigid. FLOWING SERIFS: Serifs curve and flow naturally, often with elongated pointed tips that sweep and curve rather than jutting out straight. The serifs at tops of letters may extend upward with flowing curves. The 'F', 'P', 'A', 'L' and other letters feature elegant curved extensions. STROKE STYLE: Letters have dramatic thick-to-thin contrast with gracefully curved transitions. The thick strokes flow and curve organically. The overall silhouette has a wavy, flowing quality with smooth S-curves and elegant arcs integrated into the gothic letterforms. TEXTURE: Subtle stone or tarnished metal texture with weathered patina. Metallic sheen with copper/bronze undertones mixing with silver/gray. SPACING: Letters are well-spaced to allow the flowing curves and extended serifs to breathe. Some serifs may gracefully reach toward adjacent letters. COLOR: Weathered silver/gray metallic with subtle blue-gray or copper tones, textured metallic finish. Pure black or dark stormy background. MOOD: Dark fantasy, gothic elegance, flowing and organic but still menacing - like haunted vines or elegant horror. The typography should feel ALIVE and FLOWING, with smooth organic curves throughout, NOT rigid or mechanical.",
  
  4: "TYPOGRAPHY STYLE: BOLD ANGULAR HEAVY METAL typography with sharp geometric letterforms. LETTERFORMS: THICK, HEAVY, CHUNKY uppercase letters with SHARP ANGULAR pointed terminals and serifs. The letters are SOLID and BOLD - very substantial stroke weight with no thin areas. CRITICAL ANGULAR STYLE: Letters have SHARP POINTED diamond-shaped or arrow-like terminals at the ends of strokes. The 'O' has pointed vertices rather than being round. The 'G' has a sharp angular tail. Letters like 'S', 'N', 'T' have sharp pointed tips at their terminals. Every stroke ending has a SHARP ANGULAR POINT or DIAMOND CUT rather than flat or rounded terminals. GEOMETRIC STRUCTURE: Letters are constructed from bold geometric shapes with hard angles. The overall silhouette is angular and aggressive with sharp points extending from letter terminals. Wide, stable letterforms with powerful presence. METALLIC TEXTURE: Chrome/silver metallic finish with strong highlights and shadows creating a 3D beveled effect. The metal appears polished and solid, reflecting light with bright specular highlights on edges. SPACING: Letters are close together, sometimes nearly touching, creating a unified powerful word block. The sharp terminals of adjacent letters may nearly interlock. COLOR: Silver/chrome/gunmetal metallic text with dramatic lighting - bright highlights on upper edges, darker shadows beneath. Pure black background. MOOD: Classic 80s heavy metal band logo, power metal, hard rock. Bold, powerful, aggressive but CLEAN and READABLE. This is solid, geometric metal typography - NOT smoky, dissolving, or ethereal.",
  
  5: "TYPOGRAPHY STYLE: Aggressive blackletter with sharp pointed extensions. LETTERFORMS: Heavy metal style blackletter with exaggerated sharp spikes and points extending from letters, angular aggressive terminals. EFFECTS: Sharp pointed protrusions, blade-like extensions, subtle metallic sheen. COLOR: White/silver text with sharp contrast on black background. MOOD: Death metal, aggressive, dangerous, weaponized typography.",
  
  6: "TYPOGRAPHY STYLE: ULTRA BOLD AGGRESSIVE BRUSH STROKE / SLASHING typography with SHARP JAGGED ANGULAR edges. LETTERFORMS: EXTREMELY THICK, CHUNKY, HEAVY uppercase letters that look PAINTED with aggressive, fast brush strokes using a VERY WIDE BRUSH. Letters are ITALICIZED/SLANTED at a strong forward angle. CRITICAL STROKE WEIGHT: The strokes must be VERY THICK and BOLD - substantial, meaty letterforms with heavy visual weight. This is NOT thin calligraphy - it's FAT, CHUNKY, POWERFUL brush strokes. Each letter should have MASSIVE stroke width. CRITICAL JAGGED EDGES: The edges of each stroke must be SHARP, JAGGED, and ANGULAR - NOT smooth or curved. The brush strokes have ROUGH, TORN, SPIKY edges with small sharp points and irregular jagged outlines along the stroke edges. Think of aggressive paint slashes with ANGULAR SERRATED edges rather than smooth flowing curves. The edges look like they were made with a dry brush or rough bristles creating sharp irregular silhouettes. ANGULAR SLANT: Strong italic/forward lean creating sense of speed and aggression. Letters look like they're in motion, rushing forward. STROKE STYLE: VERY BOLD, VERY THICK strokes with JAGGED edges and dramatic tapered points at terminals. Sharp angular cuts where strokes end. The 'O' and 'T' and other letters have aggressive pointed flourishes extending from them with SHARP ANGULAR character. Some strokes extend past the letter body as dynamic slashes or flicks with jagged torn edges. TEXTURE: Solid color with ROUGH JAGGED brush texture showing sharp edge irregularities. NO smooth curves. Clean background but ANGULAR letter edges. COLOR: Pure white or off-white text on pure black background. High contrast, clean and punchy. MOOD: Aggressive rock/metal logo, action movie titles, dynamic sports branding. Fast, powerful, in-your-face energy with ULTRA BOLD JAGGED brush stroke dynamism.",
  
  7: "TYPOGRAPHY STYLE: EXTREME DEATH METAL / BLACK METAL typography with SHARP SPIKY EXTENSIONS radiating from letters. LETTERFORMS: ULTRA THICK, EXTRA BOLD, CHUNKY uppercase letters with MANY SHARP POINTED SPIKES and thorny extensions shooting outward from the letterforms in all directions. CRITICAL STROKE WEIGHT: The main letter bodies must be VERY THICK, HEAVY, and BOLD with substantial meaty stroke width - NOT thin or wispy. Each letterform should have MASSIVE visual weight and presence. The letters are FAT and CHUNKY at their core. CRITICAL SPIKE STYLE: ABUNDANT sharp pointed spikes, thorns, and blade-like extensions radiate OUT from the THICK letter bodies - extending upward, downward, and diagonally. These are NOT subtle - they are dramatic, long, sharp protrusions that make the text look dangerous and weaponized. Some spikes cross over between letters. The overall silhouette is chaotic and spiky like a thorny mass or barbed wire. LETTERFORM CONSTRUCTION: Letters are constructed with THICK, HEAVY, BOLD angular strokes. The main vertical and horizontal strokes are FAT and SOLID. Vertical strokes may have rough/torn edges. Letters like 'O', 'G', 'S' have aggressive pointed forms rather than curves. The 'T', 'I', 'L' have multiple spike extensions from their THICK bodies. Every letter has several sharp protrusions extending from it while maintaining BOLD CHUNKY letterforms. TEXTURE: Solid white with possible subtle worn or rough texture. The spikes are clean and sharp. NO glitch effects, NO digital distortion, NO scan lines. COLOR: Pure white spiky text on pure black background. High contrast, clean but chaotic. MOOD: Extreme death metal, black metal band logos, brutal and aggressive. The text should look DANGEROUS with abundant sharp thorny spikes radiating from every THICK BOLD letter.",
  
  8: "TYPOGRAPHY STYLE: EXTREME DEATH METAL / BLACK METAL typography with ELABORATE CURVED SPIKES and CHROME METALLIC finish. LETTERFORMS: TALL, ORNATE, BOLD uppercase letters with THICK CHUNKY strokes and ELABORATE CURVING SPIKE EXTENSIONS that flow and twist outward from the letterforms. CRITICAL STROKE WEIGHT: The main letter bodies must be THICK, BOLD, and HEAVY - NOT thin or wispy. Each letterform should have substantial stroke width with CHUNKY vertical strokes. The letters have a gothic blackletter base but with dramatic CURVED and SWIRLING pointed extensions. CRITICAL SPIKE STYLE: Long CURVING spikes and tendrils extend from the THICK letter bodies - these are NOT straight but have elegant CURVES and SWIRLS while remaining sharp and pointed. The spikes themselves taper from THICK bases to sharp points. Extensions flow upward, downward, and diagonally with graceful arcs. Some extensions interweave between letters. LETTERFORM CONSTRUCTION: Gothic blackletter-inspired letters with BOLD HEAVY strokes. Tall proportions but with SUBSTANTIAL THICKNESS. Each letter has multiple curving spike extensions flowing from its CHUNKY body. The vertical strokes are FAT and SOLID. The 'S', 'O', 'G' have elaborate curved points with THICK main strokes. METALLIC FINISH: Polished chrome/silver metallic surface with bright specular highlights and reflections. The metal appears shiny and dimensional with light catching the THICK curved surfaces. TEXTURE: Smooth polished chrome with bright highlights on the raised BOLD sections. Dark shadows in the recessed areas create depth. COLOR: Silver/chrome metallic text with dramatic lighting - bright white highlights on curves, dark shadows beneath. Pure black background. MOOD: Technical death metal, progressive black metal band logos. Ornate, elaborate, flowing yet aggressive. BOLD THICK letterforms with intricate curved flowing spike extensions.",
  
  9: "TYPOGRAPHY STYLE: BOLD 3D BEVELED HEAVY METAL typography with chrome/steel metallic finish and INTERLOCKING LETTER ARRANGEMENT. LETTERFORMS: CHUNKY, BOLD, GEOMETRIC uppercase letters with STRONG 3D BEVELED EDGES creating dimensional depth. The letters are WIDE and HEAVY with angular geometric construction. Think classic 80s heavy metal band logos (AC/DC, Iron Maiden style). CRITICAL INTERLOCKING LAYOUT: Letters must INTERLOCK and NEST together like a unified logo lockup. Adjacent letters fit into each other's negative space - letters sit beside, above, and below each other to form a COMPACT UNIFIED BLOCK. The spacing is EXTREMELY TIGHT with letters almost touching or overlapping. For multi-word titles, words stack vertically and letters from different rows interlock - a descending letter from the top word may nestle beside or between letters of the bottom word. The overall shape forms a cohesive LOGO BLOCK, not separated words. CRITICAL 3D BEVEL: Each letter has prominent BEVELED EDGES with bright highlights on top/left edges and dark shadows on bottom/right edges creating a strong 3D extruded effect. The bevels are SHARP and GEOMETRIC with hard angular cuts. Letters appear to be made of solid polished metal with dimensional thickness. LETTERFORM CONSTRUCTION: Bold condensed uppercase with sharp angular terminals and pointed geometric serifs. The 'S' has sharp angular curves. The 'O' may have angular facets. Letters have extensions and angular points that reach toward adjacent letters, helping them interlock. METALLIC FINISH: Polished chrome/steel/gunmetal surface with dramatic lighting. Bright specular highlights on beveled top edges, dark shadows on bottom edges. COLOR: Silver/chrome/gunmetal metallic text with dramatic 3D lighting - bright white highlights on bevels, dark gray/black shadows for depth. Pure black or dark textured background. MOOD: Classic 80s heavy metal, hard rock, power metal. Bold, powerful, iconic. The text should look like a UNIFIED INTERLOCKING METAL LOGO with letters nested tightly together.",
  
  10: "TYPOGRAPHY STYLE: AGGRESSIVE SLANTED CHROME METAL typography with dynamic speed and motion. LETTERFORMS: BOLD, CHUNKY uppercase letters with STRONG ITALIC/SLANT angle creating sense of speed and forward motion. The letters are WIDE and HEAVY with sharp angular cuts. Think 80s action movie titles, racing logos, or aggressive sports branding. CRITICAL SLANT AND MOTION: Letters are HEAVILY ITALICIZED at a dramatic forward angle (approximately 15-20 degrees). The slant creates dynamic energy and forward momentum. Letters appear to be rushing/moving forward with speed. CRITICAL ANGULAR STYLE: Letters have SHARP ANGULAR CUTS and pointed terminals. The ends of strokes have diagonal cuts rather than flat or rounded terminals. Some letters may have speed line details or sharp pointed accents extending from them. The 'S', 'G', 'O' have angular geometric forms. METALLIC FINISH: Polished chrome/silver metallic surface with dramatic lighting creating 3D depth. Bright specular highlights on top/left edges, darker shadows on bottom/right. The metal has a sleek reflective quality with subtle gradient from light to dark across the letterforms. SPEED ELEMENTS: Optional subtle speed lines or motion blur effects trailing behind letters. Sharp pointed accents may extend from letter terminals suggesting speed. STROKE STYLE: BOLD and CHUNKY with substantial weight. Letters are condensed but heavy. Strong thick-to-thin contrast with the slant. COLOR: Silver/chrome/white metallic text with dramatic lighting on pure black background. High contrast with bright highlights and deep shadows. MOOD: Action movie titles, racing, extreme sports, aggressive speed. Fast, powerful, dynamic motion. The text should look like it's MOVING FAST with aggressive slanted chrome metal energy."
};

const FUTURISTIC_VARIANT_DESCRIPTIONS: Record<number, string> = {
  1: "TYPOGRAPHY STYLE: BOLD ANGULAR SLANTED 3D CHROME typography with sharp beveled metallic edges. LETTERFORMS: THICK, HEAVY, BOLD uppercase italic/slanted sans-serif with STRONG 3D BEVELED EDGES - NOT cursive script, NOT thin, NOT rounded. Letters are CHUNKY and ANGULAR with a dramatic forward slant (15-20 degrees). Think 80s action movie titles, Fast & Furious style chrome text, sports car branding. CRITICAL 3D BEVEL: Each letter has prominent BEVELED METALLIC EDGES with bright chrome highlights on top/left and darker shadows on bottom/right creating strong dimensional depth. The bevel is SHARP and GEOMETRIC with hard angular cuts. CRITICAL ANGULAR STYLE: Letters have SHARP POINTED terminals and angular cuts - NOT soft or rounded. The letterforms are geometric and aggressive with speed-inspired angles. METALLIC FINISH: Polished chrome/silver mirror finish with dramatic specular highlights and reflections. The metal surface is smooth and reflective like car chrome. Star sparkle lens flares at key highlight points. SLANT: Strong italic forward lean creating sense of speed and motion. All letters slant at the same aggressive angle. COLOR: Silver chrome with bright white specular highlights and darker chrome shadows on dark background. MOOD: 80s action movie, racing, sports cars, aggressive speed, powerful chrome metal energy.",
  
  2: "TYPOGRAPHY STYLE: SLEEK SHORT MODERN CHROME text with subtle scanline/speedline texture (matches the V2 thumbnail). LETTERFORMS: Modern geometric uppercase sans-serif with MEDIUM height (NOT tall/condensed) and a WIDE, low-profile feel. Strokes are medium weight and clean; corners are slightly rounded/softened. CRITICAL PROPORTIONS: The text should feel SHORT and SLEEK horizontally — not elongated vertically, not monument/terminal tall. SPACING: Moderate tracking (not ultra tight, not huge gaps) so the wordmark feels clean and premium. SIGNATURE TEXTURE: Add subtle horizontal streak/scanline lines THROUGH the letter interiors (like fine brushed lines or speedlines), especially on the left side of letters — this is the key V2 look. METALLIC FINISH: Cool silver/chrome with a gentle light-to-dark gradient and crisp specular highlights (top/front highlights, darker inner shading). SUBTLE GLOW: Soft, minimal outer glow/rim light around the letters for a futuristic sheen (not neon). OPTIONAL SPARKLES: Small delicate highlight sparkles on a couple of edges only. COLOR: Silver/chrome on black background. MOOD: Clean modern sci‑fi, premium tech, sleek and restrained.",
  
  3: "TYPOGRAPHY STYLE: BOLD THICK 3D EXTRUDED CHROME typography with angular stylized cuts and TIGHT letter spacing. LETTERFORMS: BOLD, HEAVY, THICK uppercase sans-serif with VERY TIGHT/CLOSE letter spacing - letters nearly touching. Angular geometric letterforms with STYLIZED DIAGONAL CUTS and notches carved into the letters for a futuristic tech look. CRITICAL 3D EXTRUSION: Strong 3D depth extrusion extending backward/downward from letters - NOT just beveled edges but actual EXTRUDED 3D DEPTH like the text is thick metal blocks. The extrusion creates dramatic dimensional depth. CRITICAL TIGHT SPACING: Letters are VERY CLOSE TOGETHER with minimal gaps - this creates a cohesive bold block of text. ANGULAR CUTS: Letters have diagonal slices, notches, and angular cuts carved into them - geometric sci-fi styling. CHROME FINISH: Polished chrome/silver metallic finish with bright specular highlights and reflections. Brushed metal texture visible. GLOW: Subtle ambient glow or rim lighting around the text edges - adds futuristic energy. COLOR: Silver chrome with bright highlights on dark background. MOOD: Bold sci-fi, action movie titles, powerful futuristic tech, aggressive chrome metal.",
  
  4: "TYPOGRAPHY STYLE: EXTRAVAGANT FUTURISTIC CHROME SERIF with DRAMATIC ELONGATED SERIFS and VERY TIGHT letter spacing. LETTERFORMS: Elegant serif font with EXAGGERATED, SWEEPING, ELONGATED SERIFS that extend dramatically - especially on letters like 'S', 'T', 'g', 'e'. The serifs are POINTED, SHARP, and ELEGANT with long sweeping extensions that give a fantasy/futuristic feel. Mixed case styling. CRITICAL PROPORTIONS: Letters must have NORMAL/STANDARD proportions - NOT tall, NOT condensed, NOT narrow. The letterforms should be WIDE and have standard x-height proportions like the thumbnail shows. Avoid any vertical stretching or condensed styling. CRITICAL TIGHT SPACING: Letters are spaced VERY CLOSE TOGETHER - nearly touching or overlapping. The tight spacing creates a connected, cohesive word block where letters flow into each other. Serifs from adjacent letters may nearly touch or interweave. CRITICAL EXTRAVAGANT SERIFS: The serifs are NOT subtle - they are DRAMATIC, ELONGATED, and POINTED. The 'S' has sweeping curved extensions. The 'T' has long elegant horizontal serifs. Letters have sharp pointed terminals that sweep outward. This creates a futuristic fantasy aesthetic, like elegant sci-fi movie titles or fantasy game logos. CHROME METALLIC FINISH: Polished silver/chrome metallic surface with dimensional sheen - soft highlights on top edges, darker shadows on bottom. Subtle 3D beveled depth to the letterforms. Elegant reflective quality. COLOR: Silver/chrome metallic with subtle warm or cool undertones on dark cinematic background. MOOD: Futuristic fantasy, elegant sci-fi, premium game titles, otherworldly sophistication. Dramatic and extravagant serif styling.",
  
  5: "TYPOGRAPHY STYLE: ULTRA-LUXURIOUS HIGH-CONTRAST DIDONE SERIF with MAXIMUM thick/thin contrast and elegant ITALIC slant. LETTERFORMS: Extremely refined uppercase and lowercase serif with DRAMATIC 15:1 thick-to-hairline stroke ratio. Thick vertical strokes are BOLD and commanding while horizontal hairlines are RAZOR THIN and delicate. Letters have elegant ITALIC/SLANTED styling with graceful forward lean. Ball terminals on letters like 'a', 'c', 'f'. Unbracketed FLAT hairline serifs. Strong vertical stress. CRITICAL CONTRAST: The thick/thin contrast must be EXTREME and DRAMATIC - the thickest strokes should be luxuriously bold while the thinnest strokes appear almost fragile. This creates maximum visual drama and elegance. CRITICAL ELEGANCE: Every letterform should feel EXQUISITELY REFINED - like high fashion typography from Vogue or Harper's Bazaar. The curves are perfectly smooth, the proportions are classically beautiful. LETTERFORM DETAILS: Letters like 'C', 'H', 'A', 'I', 'N', 'E', 'D' should showcase dramatic thick verticals with hairline horizontals and serifs. Lowercase letters have elegant x-height with refined details. SPACING: Elegant generous letter-spacing that allows each beautiful letterform to breathe. IMPORTANT: Ensure ALL letters render correctly and completely - every character must be fully formed and legible. COLOR: Elegant off-white, cream, ivory, or warm white on dark moody backgrounds OR rich warm tones that complement the artwork. MOOD: Ultimate high fashion, luxury editorial, timeless Didone elegance, refined extravagance, magazine cover sophistication.",
  
  6: "TYPOGRAPHY STYLE: BLOCKY CHUNKY HIGH-CONTRAST SERIF with EXAGGERATED POINTED SERIFS and EXTREMELY TIGHT letter spacing. LETTERFORMS: THICK, BLOCKY, CHUNKY uppercase SERIF font with dramatic thick/thin stroke contrast. The letterforms are WIDE and SHORT in proportion - NOT tall or condensed. Letters should feel SQUAT and CHUNKY with substantial horizontal width. CRITICAL PROPORTIONS: Letters must be SHORT and WIDE - blocky proportions with low height-to-width ratio. NOT tall, NOT condensed, NOT narrow. The text should feel squat and powerful. CRITICAL EXAGGERATED SERIFS: The serifs are DRAMATIC and POINTED - sharp triangular serifs that extend boldly from the letterforms. The serifs on letters like 'S', 'T', 'O', 'N', 'G' have sharp pointed tips that create an aggressive elegant look. The 'S' has dramatic pointed terminals. Serifs are NOT subtle - they are bold design elements. CRITICAL TIGHT SPACING: Letters are spaced EXTREMELY CLOSE TOGETHER - nearly touching or overlapping. The tight spacing creates a connected, cohesive word block with minimal gaps. This is essential to the style. HIGH CONTRAST: Thick verticals are VERY BOLD and chunky while some strokes thin dramatically, creating elegant contrast within the blocky forms. CLEAN STYLING: NO effects, NO glow - pure bold typography. The impact comes from the chunky letterforms, exaggerated serifs, and ultra-tight spacing. COLOR: Text color should complement the cover artwork - can be warm earth tones, white, or colors that match the scene. Dark cinematic background. MOOD: Bold editorial, chunky premium serif, powerful magazine headlines. Blocky and commanding with dramatic pointed serifs.",
  
  7: "TYPOGRAPHY STYLE: SHORT WIDE GEOMETRIC SANS-SERIF with ANGULAR CUTS/NOTCHES and MEDIUM-BOLD weight - clean and precise, NOT ultra-heavy blocky. LETTERFORMS: SHORT and WIDE uppercase letters with SQUAT proportions - letters are wider than they are tall. CRITICAL MEDIUM WEIGHT: The stroke weight should be MEDIUM-BOLD - substantial but NOT ultra-thick or chunky. Clean precise strokes, NOT heavy blocky mass. Think sleek tech font, not industrial block letters. CRITICAL ANGULAR CUTS: Letters have SHARP DIAGONAL SLICES/NOTCHES cut into them - geometric angular cuts carved into the letterforms. The 'O' has angular notched corners (like a squared O with cuts). The 'S' has angular geometric construction with cuts. These cuts are precise and clean. CRITICAL SHORT WIDE PROPORTIONS: Letters must be SHORT in height and WIDE horizontally. Squat, wide, compact - NOT tall, NOT condensed. Each letter is wider than it is tall. CRITICAL ALL SHARP CORNERS: Every corner is SHARP and ANGULAR - absolutely NO rounded edges anywhere. The 'O' is angular/squared with sharp corners, NOT round. TIGHT SPACING: Letters are close together with minimal gaps. CLEAN STYLE: Solid filled letters, clean precise edges, NO texture, NO distortion. COLOR: White or warm orange/gold tones on dark backgrounds. MOOD: Sleek futuristic tech, clean modern sci-fi, precise geometric styling.",
  
  8: "TYPOGRAPHY STYLE: ULTRA HIGH-CONTRAST DIDONE SERIF with INTERLOCKING CONNECTED LETTERS that click and nest together. LETTERFORMS: Refined mixed-case serif with MAXIMUM thick/thin stroke contrast - thick verticals are BOLD while horizontal hairlines are RAZOR THIN. Ball terminals, unbracketed flat serifs, strong vertical stress. CRITICAL INTERLOCKING SPACING: Letters must CONNECT, INTERLOCK, and NEST INTO EACH OTHER like puzzle pieces clicking together. The spacing is EXTREMELY TIGHT with letters overlapping and sharing space. The descender of one letter tucks under the next letter. The crossbar of 't' extends into adjacent letters. The tail of 'g' or 'y' interlocks with nearby characters. Letters fit together as a UNIFIED CONNECTED UNIT, not separate characters. Ligatures where letters share strokes or connect. CRITICAL CONNECTION: This is the KEY feature - letters must feel like they CLICK TOGETHER and INTERLOCK, creating a cohesive word where characters share space and nest into each other's forms. The 'L' in 'Lost' for example would connect into the 'o'. ELEGANT PROPORTIONS: Classic Didone proportions with refined curves and dramatic contrast. Mixed case with elegant uppercase and refined lowercase. TEXTURE: Subtle paper/grain texture on the letterforms. COLOR: Warm cream, beige, ivory, or golden tones that complement the artwork - NOT pure white. MOOD: High fashion editorial, luxury magazine covers, elegant interlocking typography where every letter connects to create a unified design.",
  
  9: "TYPOGRAPHY STYLE: BOLD ITALIC SLANTED SANS-SERIF with SHARP POINTED TERMINALS extending from letters. LETTERFORMS: BOLD, CHUNKY, HEAVY uppercase letters with strong ITALIC/FORWARD SLANT angle creating speed and motion. The letters are THICK and POWERFUL with substantial stroke weight. CRITICAL SHARP POINTED TERMINALS: Letters have SHARP POINTED TIPS/SPIKES extending from the ends of strokes - like aggressive racing/sports typography. The 'S' has sharp pointed ends, the 'O' has angular pointed corners, the 'N' and 'G' have sharp terminal extensions. These pointed tips give the text an aggressive, fast, dynamic feel. CRITICAL ITALIC SLANT: All letters are SLANTED/ITALICIZED at a dramatic forward angle (15-20 degrees) creating sense of speed and forward motion. ANGULAR CONSTRUCTION: Letters are geometric and angular with sharp corners - NOT rounded. The curves of letters like 'S', 'O', 'G' are angular rather than smooth. TIGHT SPACING: Letters are spaced close together, creating a cohesive unified word block. NO EFFECTS: Clean solid typography - no glow, no glitch, no matrix, no distortion. Pure bold aggressive letterforms. COLOR: Pure white on solid black background. MOOD: Racing, action movie titles, sports branding, aggressive speed, dynamic motion energy.",
  
  10: "TYPOGRAPHY STYLE: BOLD CHUNKY ANGULAR SANS-SERIF with SHARP POINTED TERMINALS and aggressive styling. LETTERFORMS: BOLD, HEAVY, CHUNKY uppercase letters with substantial stroke weight. The letters are WIDE and POWERFUL with thick solid strokes. CRITICAL SHARP POINTED TERMINALS: Letters have SHARP POINTED TIPS/EXTENSIONS at the ends of strokes - angular pointed terminals that give the text an aggressive, dynamic feel. The 'S' has sharp pointed ends, the 'O' has angular pointed corners, letters like 'T', 'I', 'L' have sharp pointed terminals extending from stroke ends. CRITICAL ANGULAR CONSTRUCTION: All letterforms are ANGULAR and GEOMETRIC - sharp corners, NOT rounded. The 'O' is angular/geometric with sharp corners, NOT round. The 'S' and 'G' have angular geometric construction. Every curve is replaced with angular facets. ITALIC SLANT: Letters have a subtle forward ITALIC/SLANT angle creating energy and motion - approximately 10-15 degrees of forward lean. STROKE WEIGHT: BOLD and CHUNKY - thick heavy strokes with substantial visual weight. This is a powerful, commanding font. TIGHT SPACING: Letters are close together, creating a unified cohesive word block. NO EFFECTS: Clean solid white typography - NO glow, NO hologram, NO 3D, NO glitch, NO neon, NO outline effects. Pure solid filled letters. COLOR: Pure white on solid black background. MOOD: Action movie titles, aggressive modern branding, powerful futuristic styling with sharp angular details.",
};

const MODERN_VARIANT_DESCRIPTIONS: Record<number, string> = {
  1: "TYPOGRAPHY STYLE: Ultra-bold condensed headline sans-serif. LETTERFORMS: Extremely heavy, very tightly spaced uppercase, maximum visual weight, newspaper headline impact. EFFECTS: None - pure typographic power through weight and scale. COLOR: Solid black on white or white on black, high contrast. MOOD: Bold journalism, impactful headlines, commanding presence.",
  
  2: "TYPOGRAPHY STYLE: Bold extended sans-serif with generous tracking. LETTERFORMS: Wide, bold sans-serif with letters spaced apart, strong horizontal emphasis. EFFECTS: Clean, no effects - typographic impact through spacing and weight. COLOR: White on dark or black on light, clean contrast. MOOD: Contemporary branding, modern luxury, confident statement.",
  
  3: "TYPOGRAPHY STYLE: Thin elegant extended sans-serif. LETTERFORMS: Ultra-light weight, wide letterforms with generous letter-spacing, refined and delicate. EFFECTS: Minimal - pure elegance through restraint. COLOR: White or light gray on dark, subtle contrast. MOOD: High fashion, luxury editorial, refined minimalism.",
  
  4: "TYPOGRAPHY STYLE: Gradient color overlay on bold sans-serif. LETTERFORMS: Bold, clean sans-serif serving as canvas for gradient. EFFECTS: Smooth gradient transition across text, modern color blending. COLOR: Vibrant gradient (pink to orange, blue to purple, etc.) on contrasting background. MOOD: Contemporary digital, fresh and energetic, social media aesthetic.",
  
  5: "TYPOGRAPHY STYLE: Bold rounded sans-serif. LETTERFORMS: Heavy weight with rounded terminals and corners, friendly geometric forms. EFFECTS: None - clean, approachable through rounded forms. COLOR: White on dark background, soft contrast. MOOD: Friendly tech, approachable modern, contemporary warmth.",
  
  6: "TYPOGRAPHY STYLE: Split/layered color offset effect. LETTERFORMS: Bold sans-serif with duplicated layers offset slightly, creating depth through color. EFFECTS: Multiple colored layers offset horizontally or vertically, risograph-style overlap. COLOR: Overlapping cyan and magenta, or complementary colors on white. MOOD: Dynamic design, energetic printing, contemporary graphic style.",
  
  7: "TYPOGRAPHY STYLE: Halftone dot pattern texture. LETTERFORMS: Bold text filled with halftone dot pattern, retro printing technique. EFFECTS: Visible dot grid pattern within letterforms, varying dot sizes for tone. COLOR: Black dots on white or colored dots on contrasting background. MOOD: Retro-modern print, pop art influence, graphic texture.",
  
  8: "TYPOGRAPHY STYLE: Clean sans-serif with soft dimensional shadow. LETTERFORMS: Medium weight, friendly sans-serif with subtle 3D depth effect. EFFECTS: Soft, slightly offset shadow creating gentle lift from surface. COLOR: White or colored text with soft gray/colored shadow. MOOD: Approachable, friendly modern, subtle dimension.",
  
  9: "TYPOGRAPHY STYLE: Geometric constructivist letterforms. LETTERFORMS: Letters built from basic geometric shapes - circles, triangles, rectangles, visible construction. EFFECTS: Visible geometric building blocks, mathematical precision. COLOR: Bold primary colors or black/white geometric forms. MOOD: Bauhaus influence, artistic construction, designed typography.",
  
  10: "TYPOGRAPHY STYLE: Organic gradient mesh flowing through text. LETTERFORMS: Sans-serif serving as container for flowing gradient mesh. EFFECTS: Smooth, organic color transitions, fluid gradient movement. COLOR: Flowing gradients of complementary colors, organic transitions. MOOD: Fluid contemporary, organic digital, smooth modern aesthetic."
};

const RETRO_VARIANT_DESCRIPTIONS: Record<number, string> = {
  1: "TYPOGRAPHY STYLE: 3D chrome script with deep extrusion. LETTERFORMS: Flowing connected script with rounded strokes, 80s chrome lettering style. EFFECTS: Deep 3D extrusion showing side faces, mirror chrome reflections, dramatic shadows. COLOR: Silver chrome with gradient from bright to shadowed, sparkle highlights. MOOD: 80s movie titles, retro luxury, nostalgic chrome.",
  
  2: "TYPOGRAPHY STYLE: Elegant neon signature script with soft glow. LETTERFORMS: Thin, delicate connected cursive like a handwritten signature, neon tube construction. EFFECTS: Soft outer glow, light bloom, subtle reflection below. COLOR: White or pastel neon with matching glow halo on dark background. MOOD: Elegant nightlife, upscale lounge, sophisticated retro.",
  
  3: "TYPOGRAPHY STYLE: Heavy groovy rounded serif. LETTERFORMS: Very thick, rounded Cooper Black style with friendly bubble proportions, 70s aesthetic. EFFECTS: Minimal - impact through bold friendly forms. COLOR: Warm colors or white on contrasting background. MOOD: 70s advertising, friendly retro, groovy warmth.",
  
  4: "TYPOGRAPHY STYLE: 8-bit pixel art serif font. LETTERFORMS: Blocky, pixelated letterforms with visible pixel grid, retro video game typography. EFFECTS: Jagged pixel edges, grid-aligned construction. COLOR: Bright arcade colors or white pixels on dark. MOOD: Retro gaming, 8-bit nostalgia, arcade aesthetic.",
  
  5: "TYPOGRAPHY STYLE: Groovy 70s flowing script. LETTERFORMS: Rounded, bouncy connected script with disco-era personality, playful curves. EFFECTS: Soft, friendly forms with smooth connections. COLOR: Warm retro palette on contrasting background. MOOD: Disco era, funky 70s, groovy vibes.",
  
  6: "TYPOGRAPHY STYLE: Chrome italic racing font with sparkles. LETTERFORMS: Bold, slanted condensed sans-serif with speed aesthetic, racing stripe feel. EFFECTS: Chrome metallic finish, lens flare sparkles, speed lines suggested. COLOR: Silver chrome with white sparkle highlights on dark. MOOD: 80s racing, sports graphics, high-speed retro.",
  
  7: "TYPOGRAPHY STYLE: Aggressive metallic brush stroke italic. LETTERFORMS: Bold, hand-painted appearance with forward slant, visible brush texture in strokes. EFFECTS: Metallic silver sheen on brush strokes, dynamic energy, speed lines. COLOR: Silver metallic on dark background with motion blur suggestion. MOOD: 80s action movies, energetic sports, dynamic retro.",
  
  8: "TYPOGRAPHY STYLE: 3D chrome heavy metal lettering. LETTERFORMS: Bold, angular letterforms with sharp points, rock/metal band aesthetic, beveled edges. EFFECTS: Deep 3D chrome extrusion, sparkle highlights, dramatic lighting. COLOR: Silver chrome with gradient depth, star sparkles on dark. MOOD: 80s rock albums, heavy metal, powerful retro.",
  
  9: "TYPOGRAPHY STYLE: Massive 3D chrome block letters. LETTERFORMS: Ultra-bold uppercase sans-serif with enormous 3D depth, cinematic scale. EFFECTS: Very deep extrusion, chrome reflections, sparkle effects, dramatic scale. COLOR: Polished chrome with deep shadows, lens flare highlights. MOOD: 80s blockbuster movies, epic scale, monumental retro.",
  
  10: "TYPOGRAPHY STYLE: Dynamic chrome brush script. LETTERFORMS: Energetic cursive painted with bold strokes, metallic finish, forward motion. EFFECTS: Chrome metallic sheen, speed lines, dynamic brush marks. COLOR: Silver chrome with motion effects on dark background. MOOD: 80s action sports, dynamic retro, energetic chrome."
};

// Helper to generate variants with detailed descriptions
const createVariantsWithDescriptions = (
  styleId: string, 
  styleName: string, 
  descriptions: Record<number, string>,
  count: number = 10
): TextStyleVariant[] => {
  return Array.from({ length: count }, (_, index) => ({
    id: `${styleId}-${index + 1}`,
    name: `V${index + 1}`,
    description: `${styleName} style variation ${index + 1}`,
    previewImage: `/text-styles/${styleId}/${styleId}-${index + 1}.png`,
    promptInstructions: descriptions[index + 1] || `Apply the ${styleName} text style as shown in the reference image. Match the exact letterforms, effects, colors, and styling.`
  }));
};

// Master configuration of all text style variants - Only 5 styles available
export const TEXT_STYLE_VARIANTS: Record<string, TextStyleVariant[]> = {
  "creative": createVariantsWithDescriptions("creative", "Creative", CREATIVE_VARIANT_DESCRIPTIONS),
  "dark": createVariantsWithDescriptions("dark", "Dark", DARK_VARIANT_DESCRIPTIONS),
  "futuristic": createVariantsWithDescriptions("futuristic", "Futuristic", FUTURISTIC_VARIANT_DESCRIPTIONS),
  "modern": createVariantsWithDescriptions("modern", "Modern", MODERN_VARIANT_DESCRIPTIONS),
  "retro": createVariantsWithDescriptions("retro", "Retro", RETRO_VARIANT_DESCRIPTIONS)
};

// Get variants for a specific text style
export function getTextStyleVariants(styleId: string): TextStyleVariant[] {
  return TEXT_STYLE_VARIANTS[styleId] || [];
}

// Check if a style has variants
export function hasVariants(styleId: string): boolean {
  return (TEXT_STYLE_VARIANTS[styleId]?.length || 0) > 0;
}

// Get all available style IDs
export function getAvailableStyleIds(): string[] {
  return Object.keys(TEXT_STYLE_VARIANTS);
}
