import { Header } from "@/components/Header";
import { HeroSection } from "@/components/HeroSection";
import { Footer } from "@/components/Footer";
import { WelcomeModal } from "@/components/WelcomeModal";
import { AnimatedDotsBackground } from "@/components/AnimatedDotsBackground";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Zap, Layers, Palette, Sun, Wand2, Image as ImageIcon } from "lucide-react";
import { Button } from "@/components/ui/button";

const exampleCovers = [
  "/examples/cover-1.jpg",
  "/examples/cover-2.jpg",
  "/examples/cover-3.jpg",
  "/examples/cover-4.jpg",
  "/examples/cover-5.jpg",
  "/examples/cover-6.jpg",
];

const Index = () => {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-8 h-8 border-3 border-primary border-t-transparent rounded-full animate-spin" />
          <span className="text-muted-foreground text-sm">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background relative">
      <WelcomeModal />
      <Header />
      
      <main className="pt-16">
        {/* Hero section */}
        <div className="relative">
          <AnimatedDotsBackground />
          <HeroSection />
        </div>
        
        {/* Example Covers Section */}
        <section id="examples" className="py-16 px-4 bg-gradient-to-b from-zinc-900/50 to-background">
          <div className="container mx-auto max-w-6xl">
            <div className="text-center mb-10">
              <h2 className="text-2xl md:text-4xl font-display tracking-wide mb-3">
                CREATED WITH <span className="text-primary">COVER ART MAKER</span>
              </h2>
              <p className="text-muted-foreground max-w-xl mx-auto">
                Professional album covers generated by artists just like you
              </p>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
              {exampleCovers.map((cover, idx) => (
                <div 
                  key={idx}
                  className="group aspect-square rounded-xl overflow-hidden border border-border hover:border-primary/50 transition-all duration-300"
                >
                  <img 
                    src={cover} 
                    alt={`Example cover ${idx + 1}`}
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                  />
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* THE STUDIOS - Bold Split Design */}
        <section className="relative py-20 md:py-32 px-4 overflow-hidden">
          {/* Dynamic background */}
          <div className="absolute inset-0">
            {/* Left side - Design Studio gradient */}
            <div className="absolute left-0 top-0 w-1/2 h-full bg-gradient-to-br from-primary/20 via-primary/5 to-transparent" />
            {/* Right side - Edit Studio gradient */}
            <div className="absolute right-0 top-0 w-1/2 h-full bg-gradient-to-bl from-white/10 via-zinc-500/5 to-transparent" />
            {/* Center glow */}
            <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-gradient-radial from-white/5 via-transparent to-transparent rounded-full blur-3xl" />
          </div>
          
          {/* Decorative line */}
          <div className="absolute left-1/2 top-20 bottom-20 w-px bg-gradient-to-b from-transparent via-border to-transparent hidden lg:block" />
          
          <div className="container mx-auto max-w-7xl relative z-10">
            {/* Main headline */}
            <div className="text-center mb-16 md:mb-24">
              <h2 className="text-4xl md:text-6xl lg:text-7xl font-display tracking-tight mb-4">
                <span className="text-foreground">TWO </span>
                <span className="relative">
                  <span className="text-primary">STUDIOS</span>
                  <svg className="absolute -bottom-2 left-0 w-full h-3 text-primary/30" viewBox="0 0 200 12" fill="none">
                    <path d="M2 10C50 2 150 2 198 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/>
                  </svg>
                </span>
              </h2>
              <p className="text-lg md:text-xl text-muted-foreground max-w-xl mx-auto">
                Professional-grade cover art creation & editing
              </p>
            </div>
            
            {/* Two Studios Grid */}
            <div className="grid lg:grid-cols-2 gap-8 lg:gap-16">
              {/* Design Studio */}
              <div className="group relative">
                {/* Floating badge */}
                <div className="absolute -top-4 left-6 z-10">
                  <div className="px-3 py-1 bg-primary text-primary-foreground text-xs font-bold rounded-full shadow-lg shadow-primary/25">
                    CREATE
                  </div>
                </div>
                
                <div className="relative p-8 md:p-10 rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/5 via-background to-background overflow-hidden">
                  {/* Glow effect */}
                  <div className="absolute -top-20 -left-20 w-40 h-40 bg-primary/20 rounded-full blur-3xl group-hover:bg-primary/30 transition-colors duration-500" />
                  
                  <div className="relative">
                    <h3 className="text-3xl md:text-4xl font-display mb-4 tracking-tight">
                      <span className="text-primary">Design</span> Studio
                    </h3>
                    
                    <p className="text-muted-foreground mb-8 text-lg leading-relaxed">
                      Describe your vision. Our AI creates stunning, unique cover art in seconds. No design skills needed.
                    </p>
                    
                    {/* Feature highlights */}
                    <div className="space-y-4 mb-8">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                          <Zap className="w-4 h-4 text-primary" />
                        </div>
                        <span className="text-sm text-foreground/80">AI generates from text prompts</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                          <Wand2 className="w-4 h-4 text-primary" />
                        </div>
                        <span className="text-sm text-foreground/80">30+ professional text styles</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                          <ImageIcon className="w-4 h-4 text-primary" />
                        </div>
                        <span className="text-sm text-foreground/80">3000×3000px streaming-ready</span>
                      </div>
                    </div>
                    
                    <Button 
                      onClick={() => user ? navigate("/design-studio") : navigate("/auth")}
                      className="w-full md:w-auto gap-2 text-base py-6 px-8"
                      size="lg"
                    >
                      Open Design Studio
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
              
              {/* Edit Studio */}
              <div className="group relative">
                {/* Floating badge */}
                <div className="absolute -top-4 left-6 z-10">
                  <div className="px-3 py-1 bg-white text-zinc-900 text-xs font-bold rounded-full shadow-lg">
                    PERFECT
                  </div>
                </div>
                
                <div className="relative p-8 md:p-10 rounded-3xl border border-white/10 bg-gradient-to-br from-white/5 via-background to-background overflow-hidden">
                  {/* Glow effect */}
                  <div className="absolute -top-20 -right-20 w-40 h-40 bg-white/10 rounded-full blur-3xl group-hover:bg-white/15 transition-colors duration-500" />
                  
                  <div className="relative">
                    <h3 className="text-3xl md:text-4xl font-display mb-4 tracking-tight">
                      <span className="bg-gradient-to-r from-zinc-200 to-zinc-400 bg-clip-text text-transparent">Edit</span> Studio
                    </h3>
                    
                    <p className="text-muted-foreground mb-8 text-lg leading-relaxed">
                      Take your covers to the next level. Add textures, lighting effects, and finishing touches.
                    </p>
                    
                    {/* Feature highlights */}
                    <div className="space-y-4 mb-8">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center">
                          <Layers className="w-4 h-4 text-white/80" />
                        </div>
                        <span className="text-sm text-foreground/80">Textures & overlay effects</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center">
                          <Sun className="w-4 h-4 text-white/80" />
                        </div>
                        <span className="text-sm text-foreground/80">Lighting & color grading</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center">
                          <Palette className="w-4 h-4 text-white/80" />
                        </div>
                        <span className="text-sm text-foreground/80">Parental advisory badges</span>
                      </div>
                    </div>
                    
                    <Button 
                      onClick={() => user ? navigate("/edit-studio") : navigate("/auth")}
                      variant="outline"
                      className="w-full md:w-auto gap-2 text-base py-6 px-8 border-white/20 hover:bg-white/5"
                      size="lg"
                    >
                      Open Edit Studio
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Bottom quality badges */}
            <div className="flex flex-wrap justify-center gap-6 mt-16 md:mt-24">
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <div className="w-2 h-2 rounded-full bg-green-500" />
                Streaming Ready
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <div className="w-2 h-2 rounded-full bg-primary" />
                3000×3000px Quality
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <div className="w-2 h-2 rounded-full bg-yellow-500" />
                100% Unique
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default Index;
