import { Header } from "@/components/Header";
import { HeroSection } from "@/components/HeroSection";
import { Footer } from "@/components/Footer";
import { WelcomeModal } from "@/components/WelcomeModal";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Zap, Layers, Palette, Sun, Wand2, Image as ImageIcon, Star, Check, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

const exampleCovers = [
  "/examples/cover-1.jpg",
  "/examples/cover-2.jpg",
  "/examples/cover-3.jpg",
  "/examples/cover-4.jpg",
  "/examples/cover-5.jpg",
  "/examples/cover-6.jpg",
];

const Index = () => {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-8 h-8 border-3 border-primary border-t-transparent rounded-full animate-spin" />
          <span className="text-muted-foreground text-sm">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background relative">
      <WelcomeModal />
      <Header />
      
      <main className="pt-16">
        {/* Hero section */}
        <HeroSection />
        
        {/* Example Covers Section - Slanted overlapping layout */}
        <section id="examples" className="relative py-16 md:py-24 px-4 bg-gradient-to-b from-zinc-900 via-zinc-900/80 to-background overflow-hidden">
          {/* Subtle glow */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-white/[0.02] rounded-full blur-[80px]" />
          
          <div className="container mx-auto max-w-6xl relative z-10">
            <div className="text-center mb-12 md:mb-16">
              <h2 className="text-2xl md:text-4xl lg:text-5xl font-display tracking-wide mb-3">
                CREATED WITH <span className="text-primary">COVER ART MAKER</span>
              </h2>
              <p className="text-muted-foreground max-w-xl mx-auto text-sm md:text-base">
                Professional album covers generated by artists just like you
              </p>
            </div>
            
            {/* Desktop - Slanted overlapping covers */}
            <div className="hidden md:flex justify-center items-end gap-[-20px] relative h-[400px]">
              {exampleCovers.map((cover, idx) => {
                const rotations = [-15, -9, -3, 3, 9, 15];
                const zIndexes = [1, 2, 3, 3, 2, 1];
                const translateY = [40, 20, 0, 0, 20, 40];
                const sizes = ['w-44', 'w-48', 'w-56', 'w-56', 'w-48', 'w-44'];
                
                return (
                  <div
                    key={idx}
                    className={`${sizes[idx]} aspect-square rounded-2xl overflow-hidden border-2 border-white/10 shadow-2xl shadow-black/50 transition-all duration-500 hover:scale-110 hover:z-50 hover:rotate-0 hover:border-primary/50 -ml-8 first:ml-0`}
                    style={{
                      transform: `rotate(${rotations[idx]}deg) translateY(${translateY[idx]}px)`,
                      zIndex: zIndexes[idx],
                    }}
                  >
                    <img 
                      src={cover} 
                      alt={`Example cover ${idx + 1}`}
                      className="w-full h-full object-cover"
                    />
                  </div>
                );
              })}
            </div>
            
            {/* Mobile - Grid layout */}
            <div className="grid grid-cols-2 gap-3 md:hidden">
              {exampleCovers.slice(0, 4).map((cover, idx) => (
                <div 
                  key={idx}
                  className="aspect-square rounded-xl overflow-hidden border border-white/10 shadow-lg"
                >
                  <img 
                    src={cover} 
                    alt={`Example cover ${idx + 1}`}
                    className="w-full h-full object-cover"
                  />
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* THE STUDIOS - Bold Split Design */}
        <section className="relative py-16 md:py-28 px-4 overflow-hidden">
          {/* Dynamic background */}
          <div className="absolute inset-0">
            <div className="absolute left-0 top-0 w-1/2 h-full bg-gradient-to-br from-primary/10 via-transparent to-transparent" />
            <div className="absolute right-0 top-0 w-1/2 h-full bg-gradient-to-bl from-white/5 via-transparent to-transparent" />
          </div>
          
          <div className="container mx-auto max-w-6xl relative z-10">
            {/* Main headline */}
            <div className="text-center mb-12 md:mb-20">
              <h2 className="text-3xl md:text-5xl lg:text-6xl font-display tracking-tight mb-4">
                <span className="text-foreground">TWO </span>
                <span className="relative">
                  <span className="text-primary">STUDIOS</span>
                </span>
              </h2>
              <p className="text-base md:text-lg text-muted-foreground max-w-xl mx-auto">
                Professional-grade cover art creation & editing
              </p>
            </div>
            
            {/* Two Studios Grid */}
            <div className="grid lg:grid-cols-2 gap-6 lg:gap-10">
              {/* Design Studio */}
              <div className="group relative">
                <div className="absolute -top-3 left-6 z-10">
                  <div className="px-3 py-1 bg-primary text-primary-foreground text-xs font-bold rounded-full shadow-lg shadow-primary/25">
                    CREATE
                  </div>
                </div>
                
                <div className="relative p-6 md:p-8 rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/5 via-background to-background overflow-hidden h-full">
                  <div className="absolute -top-20 -left-20 w-40 h-40 bg-primary/15 rounded-full blur-3xl group-hover:bg-primary/25 transition-colors duration-500" />
                  
                  <div className="relative">
                    <h3 className="text-2xl md:text-3xl font-display mb-3">
                      <span className="text-primary">Design</span> Studio
                    </h3>
                    
                    <p className="text-muted-foreground mb-6 text-sm md:text-base leading-relaxed">
                      Describe your vision. Our AI creates stunning, unique cover art in seconds.
                    </p>
                    
                    <div className="space-y-3 mb-6">
                      <div className="flex items-center gap-3">
                        <div className="w-7 h-7 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                          <Zap className="w-3.5 h-3.5 text-primary" />
                        </div>
                        <span className="text-sm text-foreground/80">AI generates from text prompts</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-7 h-7 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                          <Wand2 className="w-3.5 h-3.5 text-primary" />
                        </div>
                        <span className="text-sm text-foreground/80">30+ professional text styles</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-7 h-7 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                          <ImageIcon className="w-3.5 h-3.5 text-primary" />
                        </div>
                        <span className="text-sm text-foreground/80">3000×3000px streaming-ready</span>
                      </div>
                    </div>
                    
                    <Button 
                      onClick={() => user ? navigate("/design-studio") : navigate("/auth")}
                      className="w-full sm:w-auto gap-2 py-5 px-6"
                    >
                      Open Design Studio
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
              
              {/* Edit Studio */}
              <div className="group relative">
                <div className="absolute -top-3 left-6 z-10">
                  <div className="px-3 py-1 bg-white text-zinc-900 text-xs font-bold rounded-full shadow-lg">
                    PERFECT
                  </div>
                </div>
                
                <div className="relative p-6 md:p-8 rounded-2xl border border-white/10 bg-gradient-to-br from-white/5 via-background to-background overflow-hidden h-full">
                  <div className="absolute -top-20 -right-20 w-40 h-40 bg-white/5 rounded-full blur-3xl group-hover:bg-white/10 transition-colors duration-500" />
                  
                  <div className="relative">
                    <h3 className="text-2xl md:text-3xl font-display mb-3">
                      <span className="bg-gradient-to-r from-zinc-200 to-zinc-400 bg-clip-text text-transparent">Edit</span> Studio
                    </h3>
                    
                    <p className="text-muted-foreground mb-6 text-sm md:text-base leading-relaxed">
                      Take your covers to the next level with textures, lighting, and effects.
                    </p>
                    
                    <div className="space-y-3 mb-6">
                      <div className="flex items-center gap-3">
                        <div className="w-7 h-7 rounded-lg bg-white/10 flex items-center justify-center flex-shrink-0">
                          <Layers className="w-3.5 h-3.5 text-white/80" />
                        </div>
                        <span className="text-sm text-foreground/80">Textures & overlay effects</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-7 h-7 rounded-lg bg-white/10 flex items-center justify-center flex-shrink-0">
                          <Sun className="w-3.5 h-3.5 text-white/80" />
                        </div>
                        <span className="text-sm text-foreground/80">Lighting & color grading</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="w-7 h-7 rounded-lg bg-white/10 flex items-center justify-center flex-shrink-0">
                          <Palette className="w-3.5 h-3.5 text-white/80" />
                        </div>
                        <span className="text-sm text-foreground/80">Parental advisory badges</span>
                      </div>
                    </div>
                    
                    <Button 
                      onClick={() => user ? navigate("/edit-studio") : navigate("/auth")}
                      variant="outline"
                      className="w-full sm:w-auto gap-2 py-5 px-6 border-white/20 hover:bg-white/5"
                    >
                      Open Edit Studio
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Social Proof & Reviews Section */}
        <section className="relative py-16 md:py-24 px-4 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-background via-zinc-900/30 to-background" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-primary/5 rounded-full blur-[120px]" />
          
          <div className="container mx-auto max-w-5xl relative z-10">
            <div className="text-center mb-12">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 mb-6">
                <Star className="w-4 h-4 text-yellow-500 fill-yellow-500" />
                <span className="text-sm text-zinc-300">Loved by Artists</span>
              </div>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-display mb-4">
                Artists <span className="text-primary">Trust</span> Us
              </h2>
              <p className="text-muted-foreground max-w-lg mx-auto text-sm md:text-base">
                Join thousands of musicians creating professional cover art
              </p>
            </div>
            
            {/* Reviews Grid */}
            <div className="grid md:grid-cols-3 gap-4 md:gap-6 mb-12">
              {[
                {
                  name: "Marcus J.",
                  role: "Hip-Hop Artist",
                  text: "Finally, cover art that matches my sound. The AI understood exactly what I needed.",
                  stars: 5
                },
                {
                  name: "Luna S.",
                  role: "Indie Producer",
                  text: "Saved me hundreds on designers. The quality is insane for the price.",
                  stars: 5
                },
                {
                  name: "DJ Krave",
                  role: "EDM Producer",
                  text: "The textures and effects in Edit Studio are game-changing. My covers stand out now.",
                  stars: 5
                }
              ].map((review, idx) => (
                <div key={idx} className="p-5 md:p-6 rounded-2xl bg-white/[0.02] border border-white/10 hover:border-white/20 transition-colors">
                  <div className="flex gap-1 mb-3">
                    {Array.from({ length: review.stars }).map((_, i) => (
                      <Star key={i} className="w-4 h-4 text-yellow-500 fill-yellow-500" />
                    ))}
                  </div>
                  <p className="text-foreground/90 text-sm md:text-base mb-4 leading-relaxed">"{review.text}"</p>
                  <div>
                    <p className="font-medium text-foreground text-sm">{review.name}</p>
                    <p className="text-muted-foreground text-xs">{review.role}</p>
                  </div>
                </div>
              ))}
            </div>
            
            {/* Stats row */}
            <div className="flex flex-wrap justify-center gap-6 md:gap-12 py-8 border-y border-white/10">
              <div className="text-center">
                <p className="text-3xl md:text-4xl font-display text-primary mb-1">10K+</p>
                <p className="text-xs md:text-sm text-muted-foreground">Covers Created</p>
              </div>
              <div className="text-center">
                <p className="text-3xl md:text-4xl font-display text-foreground mb-1">4.9★</p>
                <p className="text-xs md:text-sm text-muted-foreground">Average Rating</p>
              </div>
              <div className="text-center">
                <p className="text-3xl md:text-4xl font-display text-foreground mb-1">30+</p>
                <p className="text-xs md:text-sm text-muted-foreground">Art Styles</p>
              </div>
              <div className="text-center">
                <p className="text-3xl md:text-4xl font-display text-foreground mb-1">24/7</p>
                <p className="text-xs md:text-sm text-muted-foreground">AI Available</p>
              </div>
            </div>
          </div>
        </section>

        {/* Final CTA Section */}
        <section className="relative py-16 md:py-24 px-4 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-t from-primary/10 via-transparent to-transparent" />
          <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-primary/20 rounded-full blur-[100px]" />
          
          <div className="container mx-auto max-w-3xl relative z-10 text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/30 mb-6">
              <Sparkles className="w-4 h-4 text-primary" />
              <span className="text-sm text-primary">Start for Free</span>
            </div>
            
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-display mb-4">
              Ready to Create Your Cover?
            </h2>
            
            <p className="text-muted-foreground mb-8 max-w-lg mx-auto text-sm md:text-base">
              Get 3 free credits to start. No credit card required. Create professional album covers in minutes.
            </p>
            
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-8">
              <Button
                size="lg"
                onClick={() => user ? navigate("/design-studio") : navigate("/auth")}
                className="gap-2 px-8 py-6 rounded-full bg-gradient-to-r from-primary to-rose-500 shadow-[0_0_40px_rgba(239,68,68,0.3)] hover:shadow-[0_0_60px_rgba(239,68,68,0.5)] transition-all"
              >
                Get Started Free
                <ArrowRight className="w-5 h-5" />
              </Button>
            </div>
            
            <div className="flex flex-wrap items-center justify-center gap-4 md:gap-6 text-xs md:text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <Check className="w-4 h-4 text-green-500" />
                3 Free Credits
              </div>
              <div className="flex items-center gap-2">
                <Check className="w-4 h-4 text-green-500" />
                No Watermarks
              </div>
              <div className="flex items-center gap-2">
                <Check className="w-4 h-4 text-green-500" />
                High Resolution
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default Index;
