import { Header } from "@/components/Header";
import { HeroSection } from "@/components/HeroSection";
import { Footer } from "@/components/Footer";
import { WelcomeModal } from "@/components/WelcomeModal";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Zap, Layers, Palette, Sun, Wand2, Image as ImageIcon, Star, Check, Sparkles, MessageCircle, Smartphone } from "lucide-react";
import { Button } from "@/components/ui/button";

const exampleCovers = [
  "/examples/cover-1.jpg",
  "/examples/cover-2.jpg",
  "/examples/cover-3.jpg",
  "/examples/cover-4.jpg",
  "/examples/cover-5.jpg",
  "/examples/cover-6.jpg",
];

const Index = () => {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-8 h-8 border-3 border-primary border-t-transparent rounded-full animate-spin" />
          <span className="text-muted-foreground text-sm">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background relative">
      <WelcomeModal />
      <Header />
      
      <main className="pt-16">
        {/* Hero section */}
        <HeroSection />
        
        {/* Example Covers Section - Flows directly from hero */}
        <section id="examples" className="relative -mt-8 md:-mt-12 py-4 md:py-6 px-4 overflow-hidden">
          <div className="absolute inset-0 bg-background" />
          
          <div className="container mx-auto max-w-6xl relative z-10">
            {/* Centered, bold text */}
            <div className="text-center mb-4 md:mb-6">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-display font-bold tracking-wide mb-2">
                CREATED WITH <span className="text-primary">COVER ART MAKER</span>
              </h2>
              <p className="text-muted-foreground text-sm font-medium">
                Professional album covers generated by artists just like you
              </p>
            </div>
            
            {/* Desktop - Horizontal tilted overlapping covers */}
            <div className="hidden md:flex justify-center items-center relative">
              <div className="flex items-center">
                {exampleCovers.map((cover, idx) => {
                  const rotations = [-4, -2, 0, 2, 4, 6];
                  
                  return (
                    <div
                      key={idx}
                      className="w-36 lg:w-44 aspect-square rounded-xl overflow-hidden border border-white/10 shadow-xl shadow-black/40 transition-all duration-500 hover:scale-110 hover:z-50 hover:rotate-0 hover:border-primary/50 -ml-5 first:ml-0"
                      style={{
                        transform: `rotate(${rotations[idx]}deg)`,
                        zIndex: idx === 2 || idx === 3 ? 3 : idx === 1 || idx === 4 ? 2 : 1,
                      }}
                    >
                      <img 
                        src={cover} 
                        alt={`Example cover ${idx + 1}`}
                        className="w-full h-full object-cover"
                        loading="eager"
                      />
                    </div>
                  );
                })}
              </div>
            </div>
            
            {/* Mobile - Grid layout */}
            <div className="grid grid-cols-2 gap-3 md:hidden">
              {exampleCovers.slice(0, 4).map((cover, idx) => (
                <div 
                  key={idx}
                  className="aspect-square rounded-xl overflow-hidden border border-white/10 shadow-lg"
                >
                  <img 
                    src={cover} 
                    alt={`Example cover ${idx + 1}`}
                    className="w-full h-full object-cover"
                    loading="eager"
                  />
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Complete Workflow Section - Studios as Steps */}
        <section className="relative py-12 md:py-16 px-4 overflow-hidden">
          {/* Background with red glow from sides */}
          <div className="absolute inset-0 bg-background" />
          <div className="absolute top-1/2 -translate-y-1/2 left-0 w-[300px] h-[500px] bg-red-600/10 rounded-full blur-[120px]" />
          <div className="absolute top-1/2 -translate-y-1/2 right-0 w-[300px] h-[500px] bg-primary/10 rounded-full blur-[120px]" />
          
          <div className="container mx-auto max-w-5xl relative z-10">
            {/* Main headline */}
            <div className="text-center mb-8 md:mb-12">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-display tracking-tight mb-2">
                <span className="text-foreground">Your Complete </span>
                <span className="text-primary">Workflow</span>
              </h2>
              <p className="text-sm md:text-base text-muted-foreground max-w-lg mx-auto">
                Generate, then perfect. Two powerful tools working together.
              </p>
            </div>
            
            {/* Connected workflow */}
            <div className="relative">
              {/* Connection line - desktop only */}
              <div className="hidden lg:block absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-16 h-px bg-gradient-to-r from-primary/50 via-white/30 to-white/50 z-20" />
              <div className="hidden lg:flex absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-30 items-center justify-center w-8 h-8 rounded-full bg-background border border-white/20">
                <ArrowRight className="w-4 h-4 text-white/60" />
              </div>
              
              <div className="grid lg:grid-cols-2 gap-4 lg:gap-8">
                {/* Step 1 - Design Studio */}
                <div className="group relative flex flex-col">
                  <div className="absolute -top-3 left-6 z-10">
                    <div className="px-3 py-1 bg-primary text-primary-foreground text-xs font-bold rounded-full shadow-lg shadow-primary/25">
                      STEP 1
                    </div>
                  </div>
                  
                  <div className="relative p-5 md:p-6 rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/5 via-background to-background overflow-hidden flex-1 flex flex-col">
                    <div className="absolute -top-20 -left-20 w-40 h-40 bg-primary/15 rounded-full blur-3xl group-hover:bg-primary/25 transition-colors duration-500" />
                    
                    <div className="relative flex-1 flex flex-col">
                      <h3 className="text-xl md:text-2xl font-display mb-2">
                        <span className="text-primary">Design</span> Studio
                      </h3>
                      
                      <p className="text-muted-foreground mb-4 text-sm leading-relaxed">
                        Generate unique cover art from text descriptions. AI creates professional designs in seconds.
                      </p>
                      
                      <div className="space-y-2 mb-4 flex-1">
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                            <Zap className="w-3 h-3 text-primary" />
                          </div>
                          <span className="text-sm text-foreground/80">AI generates from text prompts</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                            <Wand2 className="w-3 h-3 text-primary" />
                          </div>
                          <span className="text-sm text-foreground/80">30+ professional text styles</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                            <ImageIcon className="w-3 h-3 text-primary" />
                          </div>
                          <span className="text-sm text-foreground/80">3000×3000px streaming-ready</span>
                        </div>
                      </div>
                      
                      <Button 
                        onClick={() => user ? navigate("/design-studio") : navigate("/auth")}
                        className="w-full sm:w-auto gap-2 py-4 px-5 text-sm mt-auto"
                      >
                        Open Design Studio
                        <ArrowRight className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
                
                {/* Step 2 - Edit Studio */}
                <div className="group relative flex flex-col">
                  <div className="absolute -top-3 left-6 z-10">
                    <div className="px-3 py-1 bg-white text-zinc-900 text-xs font-bold rounded-full shadow-lg">
                      STEP 2
                    </div>
                  </div>
                  
                  <div className="relative p-5 md:p-6 rounded-2xl border border-white/10 bg-gradient-to-br from-white/5 via-background to-background overflow-hidden flex-1 flex flex-col">
                    <div className="absolute -top-20 -right-20 w-40 h-40 bg-white/5 rounded-full blur-3xl group-hover:bg-white/10 transition-colors duration-500" />
                    
                    <div className="relative flex-1 flex flex-col">
                      <h3 className="text-xl md:text-2xl font-display mb-2">
                        <span className="bg-gradient-to-r from-zinc-200 to-zinc-400 bg-clip-text text-transparent">Edit</span> Studio
                      </h3>
                      
                      <p className="text-muted-foreground mb-4 text-sm leading-relaxed">
                        Perfect your covers with textures, lighting effects, and finishing touches.
                      </p>
                      
                      <div className="space-y-2 mb-4 flex-1">
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-lg bg-white/10 flex items-center justify-center flex-shrink-0">
                            <Layers className="w-3 h-3 text-white/80" />
                          </div>
                          <span className="text-sm text-foreground/80">Textures & overlay effects</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-lg bg-white/10 flex items-center justify-center flex-shrink-0">
                            <Sun className="w-3 h-3 text-white/80" />
                          </div>
                          <span className="text-sm text-foreground/80">Lighting & color grading</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 rounded-lg bg-white/10 flex items-center justify-center flex-shrink-0">
                            <Palette className="w-3 h-3 text-white/80" />
                          </div>
                          <span className="text-sm text-foreground/80">Parental advisory badges</span>
                        </div>
                      </div>
                      
                      <Button 
                        onClick={() => user ? navigate("/edit-studio") : navigate("/auth")}
                        variant="outline"
                        className="w-full sm:w-auto gap-2 py-4 px-5 text-sm border-white/20 hover:bg-white/5 mt-auto"
                      >
                        Open Edit Studio
                        <ArrowRight className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Social Proof & Reviews Section - White/Silver background for trust */}
        <section className="relative py-12 md:py-16 px-4 overflow-hidden">
          {/* Light gradient background for trust */}
          <div className="absolute inset-0 bg-gradient-to-b from-background via-zinc-900/60 to-zinc-700/30" />
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-white/8 rounded-full blur-[150px]" />
          <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[700px] h-[350px] bg-zinc-300/10 rounded-full blur-[130px]" />
          
          <div className="container mx-auto max-w-4xl relative z-10">
            <div className="text-center mb-8">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 border border-white/20 mb-4">
                <Star className="w-4 h-4 text-yellow-500 fill-yellow-500" />
                <span className="text-sm text-zinc-200">Loved by Artists</span>
              </div>
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-display mb-2">
                Artists <span className="text-primary">Trust</span> Us
              </h2>
              <p className="text-muted-foreground max-w-md mx-auto text-sm">
                Join thousands of musicians creating professional cover art
              </p>
            </div>
            
            {/* Reviews Grid */}
            <div className="grid md:grid-cols-3 gap-3 md:gap-4 mb-8">
              {[
                {
                  name: "Marcus J.",
                  role: "Hip-Hop Artist",
                  text: "Finally, cover art that matches my sound. The AI understood exactly what I needed.",
                  stars: 5
                },
                {
                  name: "Luna S.",
                  role: "Indie Producer",
                  text: "Saved me hundreds on designers. The quality is insane for the price.",
                  stars: 5
                },
                {
                  name: "DJ Krave",
                  role: "EDM Producer",
                  text: "The textures and effects in Edit Studio are game-changing. My covers stand out now.",
                  stars: 5
                }
              ].map((review, idx) => (
                <div key={idx} className="p-4 md:p-5 rounded-xl bg-white/[0.03] border border-white/15 hover:border-white/25 transition-colors backdrop-blur-sm">
                  <div className="flex gap-1 mb-2">
                    {Array.from({ length: review.stars }).map((_, i) => (
                      <Star key={i} className="w-3.5 h-3.5 text-yellow-500 fill-yellow-500" />
                    ))}
                  </div>
                  <p className="text-foreground/90 text-sm mb-3 leading-relaxed">"{review.text}"</p>
                  <div>
                    <p className="font-medium text-foreground text-sm">{review.name}</p>
                    <p className="text-muted-foreground text-xs">{review.role}</p>
                  </div>
                </div>
              ))}
            </div>
            
            {/* Stats row */}
            <div className="flex flex-wrap justify-center gap-6 md:gap-10 py-5 border-y border-white/15">
              <div className="text-center">
                <p className="text-2xl md:text-3xl font-display text-primary mb-1">10K+</p>
                <p className="text-xs text-muted-foreground">Covers Created</p>
              </div>
              <div className="text-center">
                <p className="text-2xl md:text-3xl font-display text-foreground mb-1">4.9★</p>
                <p className="text-xs text-muted-foreground">Average Rating</p>
              </div>
              <div className="text-center">
                <p className="text-2xl md:text-3xl font-display text-foreground mb-1">30+</p>
                <p className="text-xs text-muted-foreground">Art Styles</p>
              </div>
              <div className="text-center">
                <p className="text-2xl md:text-3xl font-display text-foreground mb-1">24/7</p>
                <p className="text-xs text-muted-foreground flex items-center justify-center gap-1">
                  <MessageCircle className="w-3 h-3" />
                  Customer Support
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Final CTA Section - Engaging with Spotify-style visual */}
        <section className="relative py-12 md:py-20 px-4 overflow-hidden">
          {/* Bright silver/white gradient background for trust */}
          <div className="absolute inset-0 bg-gradient-to-b from-zinc-800/40 via-zinc-700/20 to-zinc-600/10" />
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-white/8 rounded-full blur-[150px]" />
          <div className="absolute top-1/3 right-1/4 w-[400px] h-[300px] bg-zinc-400/10 rounded-full blur-[120px]" />
          
          <div className="container mx-auto max-w-5xl relative z-10">
            <div className="flex flex-col lg:flex-row items-center gap-8 lg:gap-16">
              {/* Visual side - Phone with Spotify-style interface showing the cover */}
              <div className="flex-1 relative hidden lg:flex justify-center">
                <div className="relative">
                  {/* Phone frame */}
                  <div className="w-72 h-[540px] rounded-[45px] border-[5px] border-zinc-500 bg-zinc-900 shadow-2xl shadow-black/60 overflow-hidden p-2">
                    <div className="w-full h-full rounded-[36px] bg-zinc-950 overflow-hidden flex flex-col">
                      {/* Status bar / notch */}
                      <div className="h-8 flex items-center justify-center">
                        <div className="w-24 h-6 bg-zinc-900 rounded-full" />
                      </div>
                      
                      {/* Spotify-style now playing screen */}
                      <div className="flex-1 p-4 flex flex-col bg-gradient-to-b from-emerald-900/60 via-zinc-950 to-zinc-950">
                        {/* Spotify header */}
                        <div className="flex items-center justify-between mb-4">
                          <div className="w-6 h-6 flex items-center justify-center">
                            <div className="w-4 h-0.5 bg-white/60" />
                          </div>
                          <span className="text-[10px] text-white/60 uppercase tracking-widest">Playing From Album</span>
                          <div className="w-6 h-6" />
                        </div>
                        
                        {/* Album cover - Large */}
                        <div className="aspect-square rounded-lg overflow-hidden shadow-2xl shadow-black/50 mb-4">
                          <img src={exampleCovers[0]} alt="Album cover" className="w-full h-full object-cover" />
                        </div>
                        
                        {/* Track info */}
                        <div className="mb-3">
                          <h4 className="text-white font-semibold text-sm truncate">Midnight Dreams</h4>
                          <p className="text-white/50 text-xs">Artist Name</p>
                        </div>
                        
                        {/* Progress bar */}
                        <div className="mb-3">
                          <div className="h-1 bg-white/20 rounded-full overflow-hidden">
                            <div className="h-full w-1/3 bg-white rounded-full" />
                          </div>
                          <div className="flex justify-between text-[9px] text-white/40 mt-1">
                            <span>1:23</span>
                            <span>3:45</span>
                          </div>
                        </div>
                        
                        {/* Playback controls */}
                        <div className="flex items-center justify-center gap-6 mt-auto mb-2">
                          <div className="w-5 h-5 text-white/60">⏮</div>
                          <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center">
                            <div className="w-0 h-0 border-l-[10px] border-l-black border-y-[6px] border-y-transparent ml-1" />
                          </div>
                          <div className="w-5 h-5 text-white/60">⏭</div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  {/* "Your cover here" badge */}
                  <div className="absolute -top-2 -right-4 px-3 py-1.5 bg-emerald-500 text-white text-xs font-bold rounded-full shadow-lg shadow-emerald-500/30 rotate-12">
                    Your cover here!
                  </div>
                  
                  {/* Floating covers showing variety */}
                  <div className="absolute -top-6 -left-16 w-24 h-24 rounded-xl overflow-hidden border-2 border-white/20 shadow-2xl rotate-[-15deg] z-10">
                    <img src={exampleCovers[4]} alt="" className="w-full h-full object-cover" />
                  </div>
                  <div className="absolute -bottom-6 -right-16 w-28 h-28 rounded-xl overflow-hidden border-2 border-white/20 shadow-2xl rotate-[10deg] z-10">
                    <img src={exampleCovers[5]} alt="" className="w-full h-full object-cover" />
                  </div>
                </div>
              </div>
              
              {/* Text side */}
              <div className="flex-1 text-center lg:text-left">
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/30 mb-4">
                  <Sparkles className="w-4 h-4 text-primary" />
                  <span className="text-sm text-primary">Start for Free</span>
                </div>
                
                <h2 className="text-2xl md:text-3xl lg:text-4xl font-display mb-3">
                  Ready to Create Your Cover?
                </h2>
                
                <p className="text-muted-foreground mb-6 max-w-md mx-auto lg:mx-0 text-sm">
                  Get 3 free credits to start. No credit card required. Create professional album covers in minutes.
                </p>
                
                <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4 mb-6">
                  <Button
                    size="lg"
                    onClick={() => user ? navigate("/design-studio") : navigate("/auth")}
                    className="gap-2 px-8 py-5 rounded-full bg-gradient-to-r from-primary to-red-600 shadow-[0_0_40px_rgba(239,68,68,0.3)] hover:shadow-[0_0_60px_rgba(239,68,68,0.5)] transition-all"
                  >
                    Get Started Free
                    <ArrowRight className="w-5 h-5" />
                  </Button>
                </div>
                
                <div className="flex flex-wrap items-center justify-center lg:justify-start gap-4 text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-green-500" />
                    3 Free Credits
                  </div>
                  <div className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-green-500" />
                    No Watermarks
                  </div>
                  <div className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-green-500" />
                    High Resolution
                  </div>
                </div>
                
                {/* Mobile visual hint */}
                <div className="lg:hidden mt-8 flex items-center justify-center gap-2 text-muted-foreground">
                  <Smartphone className="w-4 h-4" />
                  <span className="text-xs">Works on any device</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default Index;
